<?xml version="1.0"?>
<package format="3">

  <name>soil_sampler_description</name>
  <version>0.1.0</version>

  <description>
    URDF and Xacro description of the robotic soil sampling implement.
  </description>

  <maintainer email="jeppha@mmmi.sdu.dk">Jeppe Hansen</maintainer>

  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>xacro</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
