float32 wind_speed_mean
float32 wind_speed_stddev

int32 wind_direction_gear
float32 wind_direction_mean
float32 wind_direction_stddev

float32 humidity_mean
float32 humidity_stddev

float32 temperature_mean
float32 temperature_stddev

float32 noise_mean
float32 noise_stddev

float32 pm2_5_mean
float32 pm2_5_stddev

float32 pm10_mean
float32 pm10_stddev

float32 pressure_mean
float32 pressure_stddev

uint32 illuminance
float32 rainfall